POST /foo HTTP/1.1
cache-control: no-cache
Content-Type: text/xml
Transfer-Encoding: chunked
Accept: */*
Host: localhost
accept-encoding: gzip, deflate

18c2
<?xml version="1.0"?>
<body>
	<list name="sections">
		<section name="section_one">
			<list name="items">
				<item name="item_one">
					item one
				</item>
				<item name="item_two">
					item two
				</item>
				<item name="item_three">
					item three
				</item>
				<item name="item_four">
					item four
				</item>
				<item name="item_five">
					item five
				</item>
				<item name="item_six">
					item six
				</item>
				<item name="item_seven">
					item seven
				</item>
				<item name="item_eight">
					item eight
				</item>
				<item name="item_nine">
					item nine
				</item>
				<item name="item_ten">
					item ten
				</item>
			</list>
		</section>
		<section name="section_two">
			<list name="items">
				<item name="item_one">
					item one
				</item>
				<item name="item_two">
					item two
				</item>
				<item name="item_three">
					item three
				</item>
				<item name="item_four">
					item four
				</item>
				<item name="item_five">
					item five
				</item>
				<item name="item_six">
					item six
				</item>
				<item name="item_seven">
					item seven
				</item>
				<item name="item_eight">
					item eight
				</item>
				<item name="item_nine">
					item nine
				</item>
				<item name="item_ten">
					item ten
				</item>
			</list>
		</section>
		<section name="section_three">
			<list name="items">
				<item name="item_one">
					item one
				</item>
				<item name="item_two">
					item two
				</item>
				<item name="item_three">
					item three
				</item>
				<item name="item_four">
					item four
				</item>
				<item name="item_five">
					item five
				</item>
				<item name="item_six">
					item six
				</item>
				<item name="item_seven">
					item seven
				</item>
				<item name="item_eight">
					item eight
				</item>
				<item name="item_nine">
					item nine
				</item>
				<item name="item_ten">
					item ten
				</item>
			</list>
		</section>
		<section name="section_four">
			<list name="items">
				<item name="item_one">
					item one
				</item>
				<item name="item_two">
					item two
				</item>
				<item name="item_three">
					item three
				</item>
				<item name="item_four">
					item four
				</item>
				<item name="item_five">
					item five
				</item>
				<item name="item_six">
					item six
				</item>
				<item name="item_seven">
					item seven
				</item>
				<item name="item_eight">
					item eight
				</item>
				<item name="item_nine">
					item nine
				</item>
				<item name="item_ten">
					item ten
				</item>
			</list>
		</section>
		<section name="section_five">
			<list name="items">
				<item name="item_one">
					item one
				</item>
				<item name="item_two">
					item two
				</item>
				<item name="item_three">
					item three
				</item>
				<item name="item_four">
					item four
				</item>
				<item name="item_five">
					item five
				</item>
				<item name="item_six">
					item six
				</item>
				<item name="item_seven">
					item seven
				</item>
				<item name="item_eight">
					item eight
				</item>
				<item name="item_nine">
					item nine
				</item>
				<item name="item_ten">
					item ten
				</item>
			</list>
		</section>
		<section name="section_six">
			<list name="items">
				<item name="item_one">
					item one
				</item>
				<item name="item_two">
					item two
				</item>
				<item name="item_three">
					item three
				</item>
				<item name="item_four">
					item four
				</item>
				<item name="item_five">
					item five
				</item>
				<item name="item_six">
					item six
				</item>
				<item name="item_seven">
					item seven
				</item>
				<item name="item_eight">
					item eight
				</item>
				<item name="item_nine">
					item nine
				</item>
				<item name="item_ten">
					item ten
				</item>
			</list>
		</section>
		<section name="section_seven">
			<list name="items">
				<item name="item_one">
					item one
				</item>
				<item name="item_two">
					item two
				</item>
				<item name="item_three">
					item three
				</item>
				<item name="item_four">
					item four
				</item>
				<item name="item_five">
					item five
				</item>
				<item name="item_six">
					item six
				</item>
				<item name="item_seven">
					item seven
				</item>
				<item name="item_eight">
					item eight
				</item>
				<item name="item_nine">
					item nine
				</item>
				<item name="item_ten">
					item ten
				</item>
			</list>
		</section>
		<section name="section_eight">
			<list name="items">
				<item name="item_one">
					item one
				</item>
				<item name="item_two">
					item two
				</item>
				<item name="item_three">
					item three
				</item>
				<item name="item_four">
					item four
				</item>
				<item name="item_five">
					item five
				</item>
				<item name="item_six">
					item six
				</item>
				<item name="item_seven">
					item seven
				</item>
				<item name="item_eight">
					item eight
				</item>
				<item name="item_nine">
					item nine
				</item>
				<item name="item_ten">
					item ten
				</item>
			</list>
		</section>
		<section name="section_nine">
			<list name="items">
				<item name="item_one">
					item one
				</item>
				<item name="item_two">
					item two
				</item>
				<item name="item_three">
					item three
				</item>
				<item name="item_four">
					item four
				</item>
				<item name="item_five">
					item five
				</item>
				<item name="item_six">
					item six
				</item>
				<item name="item_seven">
					item seven
				</item>
				<item name="item_eight">
					item eight
				</item>
				<item name="item_nine">
					item nine
				</item>
				<item name="item_ten">
					item ten
				</item>
			</list>
		</section>
		<section name="section_ten">
			<list name="items">
				<item name="item_one">
					item one
				</item>
				<item name="item_two">
					item two
				</item>
				<item name="item_three">
					item three
				</item>
				<item name="item_four">
					item four
				</item>
				<item name="item_five">
					item five
				</item>
				<item name="item_six">
					item six
				</item>
				<item name="item_seven">
					item seven
				</item>
				<item name="item_eight">
					item eight
				</item>
				<item name="item_nine">
					item nine
				</item>
				<item name="item_ten">
					item ten
				</item>
			</list>
		</section>
	</list>
</body>
0
