POST /foo HTTP/1.1
cache-control: no-cache
Content-Type: application/json
Transfer-Encoding: chunked
Accept: */*
Host: localhost
accept-encoding: gzip, deflate

268
{
  "items": [
    {
      "name": "item_0",
      "index": 0
    },
    {
      "name": "item_1",
      "index": 1
    },
    {
      "name": "item_2",
      "index": 2
    },
    {
      "name": "item_3",
      "index": 3
    },
    {
      "name": "item_4",
      "index": 4
    },
    {
      "name": "item_5",
      "index": 5
    },
    {
      "name": "item_6",
      "index": 6
    },
    {
      "name": "item_7",
      "index": 7
    },
    {
      "name": "item_8",
      "index": 8
    },
    {
      "name": "item_9",
      "index": 9
    },
    {
      "name": "item_10",
      "index": 10
    }
  ]
}

0
